0 0 dataAuditErrors
83 0 offGridShapeErrors: off grid polygon on layer Bondpad
86 0 offGridShapeErrors: off grid polygon on layer CapMetal
89 0 offGridShapeErrors: off grid polygon on layer Cont
92 0 offGridShapeErrors: off grid polygon on layer ESDdummy
95 0 offGridShapeErrors: off grid polygon on layer INDdummy
98 0 offGridShapeErrors: off grid polygon on layer M1Resdum
101 0 offGridShapeErrors: off grid polygon on layer M2Resdum
104 0 offGridShapeErrors: off grid polygon on layer M3Resdum
107 0 offGridShapeErrors: off grid polygon on layer M4Resdum
110 0 offGridShapeErrors: off grid polygon on layer M5Resdum
113 0 offGridShapeErrors: off grid polygon on layer M6Resdum
116 0 offGridShapeErrors: off grid polygon on layer M7Resdum
119 0 offGridShapeErrors: off grid polygon on layer M8Resdum
122 0 offGridShapeErrors: off grid polygon on layer M9Resdum
125 0 offGridShapeErrors: off grid polygon on layer M10Resdum
128 0 offGridShapeErrors: off grid polygon on layer M11Resdum
131 0 offGridShapeErrors: off grid polygon on layer Metal1
134 0 offGridShapeErrors: off grid polygon on layer Metal2
137 0 offGridShapeErrors: off grid polygon on layer Metal3
140 0 offGridShapeErrors: off grid polygon on layer Metal4
143 0 offGridShapeErrors: off grid polygon on layer Metal5
146 0 offGridShapeErrors: off grid polygon on layer Metal6
149 0 offGridShapeErrors: off grid polygon on layer Metal7
152 0 offGridShapeErrors: off grid polygon on layer Metal8
155 0 offGridShapeErrors: off grid polygon on layer Metal9
158 0 offGridShapeErrors: off grid polygon on layer Metal10
161 0 offGridShapeErrors: off grid polygon on layer Metal11
164 0 offGridShapeErrors: off grid polygon on layer NPNdummy
167 0 offGridShapeErrors: off grid polygon on layer Nburied
170 0 offGridShapeErrors: off grid polygon on layer Nhvt
173 0 offGridShapeErrors: off grid polygon on layer Nimp
176 0 offGridShapeErrors: off grid polygon on layer Nlvt
179 0 offGridShapeErrors: off grid polygon on layer Nwell
182 0 offGridShapeErrors: off grid polygon on layer Nzvt
185 0 offGridShapeErrors: off grid polygon on layer Oxide
188 0 offGridShapeErrors: off grid polygon on layer Oxide_thk
191 0 offGridShapeErrors: off grid polygon on layer PNPdummy
194 0 offGridShapeErrors: off grid polygon on layer Phvt
197 0 offGridShapeErrors: off grid polygon on layer Pimp
200 0 offGridShapeErrors: off grid polygon on layer Plvt
203 0 offGridShapeErrors: off grid polygon on layer Poly
206 0 offGridShapeErrors: off grid polygon on layer Psub
209 0 offGridShapeErrors: off grid polygon on layer ResWdum
212 0 offGridShapeErrors: off grid polygon on layer Resdum
215 0 offGridShapeErrors: off grid polygon on layer SiProt
218 0 offGridShapeErrors: off grid polygon on layer Via1
221 0 offGridShapeErrors: off grid polygon on layer Via2
224 0 offGridShapeErrors: off grid polygon on layer Via3
227 0 offGridShapeErrors: off grid polygon on layer Via4
230 0 offGridShapeErrors: off grid polygon on layer Via5
233 0 offGridShapeErrors: off grid polygon on layer Via6
236 0 offGridShapeErrors: off grid polygon on layer Via7
239 0 offGridShapeErrors: off grid polygon on layer Via8
242 0 offGridShapeErrors: off grid polygon on layer Via9
245 0 offGridShapeErrors: off grid polygon on layer Via10
247 0 non45 degree polygon on layer Bondpad
249 0 non45 degree polygon on layer CapMetal
251 0 non45 degree polygon on layer Cont
253 0 non45 degree polygon on layer ESDdummy
255 0 non45 degree polygon on layer INDdummy
257 0 non45 degree polygon on layer M1Resdum
259 0 non45 degree polygon on layer M2Resdum
261 0 non45 degree polygon on layer M3Resdum
263 0 non45 degree polygon on layer M4Resdum
265 0 non45 degree polygon on layer M5Resdum
267 0 non45 degree polygon on layer M6Resdum
269 0 non45 degree polygon on layer M7Resdum
271 0 non45 degree polygon on layer M8Resdum
273 0 non45 degree polygon on layer M9Resdum
275 0 non45 degree polygon on layer M10Resdum
277 0 non45 degree polygon on layer M11Resdum
279 0 non45 degree polygon on layer Metal1
281 0 non45 degree polygon on layer Metal2
283 0 non45 degree polygon on layer Metal3
285 0 non45 degree polygon on layer Metal4
287 0 non45 degree polygon on layer Metal5
289 0 non45 degree polygon on layer Metal6
291 0 non45 degree polygon on layer Metal7
293 0 non45 degree polygon on layer Metal8
295 0 non45 degree polygon on layer Metal9
297 0 non45 degree polygon on layer Metal10
299 0 non45 degree polygon on layer Metal11
301 0 non45 degree polygon on layer NPNdummy
303 0 non45 degree polygon on layer Nburied
305 0 non45 degree polygon on layer Nhvt
307 0 non45 degree polygon on layer Nimp
309 0 non45 degree polygon on layer Nlvt
311 0 non45 degree polygon on layer Nwell
313 0 non45 degree polygon on layer Nzvt
315 0 non45 degree polygon on layer Oxide
317 0 non45 degree polygon on layer Oxide_thk
319 0 non45 degree polygon on layer PNPdummy
321 0 non45 degree polygon on layer Phvt
323 0 non45 degree polygon on layer Pimp
325 0 non45 degree polygon on layer Plvt
327 0 non45 degree polygon on layer Poly
329 0 non45 degree polygon on layer Psub
331 0 non45 degree polygon on layer ResWdum
333 0 non45 degree polygon on layer Resdum
335 0 non45 degree polygon on layer SiProt
337 0 non45 degree polygon on layer Via1
339 0 non45 degree polygon on layer Via2
341 0 non45 degree polygon on layer Via3
343 0 non45 degree polygon on layer Via4
345 0 non45 degree polygon on layer Via5
347 0 non45 degree polygon on layer Via6
349 0 non45 degree polygon on layer Via7
351 0 non45 degree polygon on layer Via8
353 0 non45 degree polygon on layer Via9
355 0 non45 degree polygon on layer Via10
356 0 acute angle on layer Bondpad
357 0 acute angle on layer ESDdummy
358 0 acute angle on layer INDdummy
359 0 acute angle on layer M1Resdum
360 0 acute angle on layer M2Resdum
361 0 acute angle on layer M3Resdum
362 0 acute angle on layer M4Resdum
363 0 acute angle on layer M5Resdum
364 0 acute angle on layer M6Resdum
365 0 acute angle on layer M7Resdum
366 0 acute angle on layer M8Resdum
367 0 acute angle on layer M9Resdum
368 0 acute angle on layer M10Resdum
369 0 acute angle on layer M11Resdum
370 0 acute angle on layer NPNdummy
371 0 acute angle on layer PNPdummy
372 0 acute angle on layer Psub
373 0 acute angle on layer ResWdum
374 0 acute angle on layer Resdum
413 0 NZVT.X.4: Only one Oxide region may be in an Nzvt region
556 0 BONDPAD.L.1: Bondpad length must be >= 68.0 um
560 0 NBL.X.1: Nburied must have an Nwell isolation ring
621 0 NZVT.O.1: Minimum and maximum Nzvt to Active Area overlap == 0.16 um
834 0 VIAk.X.3_VIAk.X.4: Metal1 through Metal6 stack must have two or more stacked Vias at all levels
839 0 VIAk.X.3_VIAk.X.4: Metal2 through Metal7 stack must have two or more stacked Vias at all levels
844 0 VIAk.X.3_VIAk.X.4: Metal3 through Metal8 stack must have two or more stacked Vias at all levels
849 0 VIAk.X.3_VIAk.X.4: Metal4 through Metal9 stack must have two or more stacked Vias at all levels
1139 0 POLY.SE.3: Maximum Poly segment length (width < 0.14) between two contacts >= 12.0 um
1148 0 VIA1.E.3: At least 2 Via1 must be used to join Metal1 and Metal2 when they are within 3.0um of a metal plate (Metal1/Metal2) when the metal plate size is has width > 1.5 and length > 1.5
1157 0 VIA2.E.3: At least 2 Via2 must be used to join Metal2 and Metal3 when they are within 3.0um of a metal plate (Metal2/Metal3) when the metal plate size is has width > 1.5 and length > 1.5
1166 0 VIA3.E.3: At least 2 Via3 must be used to join Metal3 and Metal4 when they are within 3.0um of a metal plate (Metal3/Metal4) when the metal plate size is has width > 1.5 and length > 1.5
1175 0 VIA4.E.3: At least 2 Via4 must be used to join Metal4 and Metal5 when they are within 3.0um of a metal plate (Metal4/Metal5) when the metal plate size is has width > 1.5 and length > 1.5
1184 0 VIA5.E.3: At least 2 Via5 must be used to join Metal5 and Metal6 when they are within 3.0um of a metal plate (Metal5/Metal6) when the metal plate size is has width > 1.5 and length > 1.5
1193 0 VIA6.E.3: At least 2 Via6 must be used to join Metal6 and Metal7 when they are within 3.0um of a metal plate (Metal6/Metal7) when the metal plate size is has width > 1.5 and length > 1.5
1202 0 VIA7.E.3: At least 2 Via7 must be used to join Metal7 and Metal8 when they are within 3.0um of a metal plate (Metal7/Metal8) when the metal plate size is has width > 1.5 and length > 1.5
1211 0 VIA8.E.3: At least 2 Via8 must be used to join Metal8 and Metal9 when they are within 3.0um of a metal plate (Metal8/Metal9) when the metal plate size is has width > 1.5 and length > 1.5
1223 0 BONDPAD.SP.5: Bondpad Metal1 slot to Bondpad Metal1 slot spacing must be == 1.50
1227 0 BONDPAD.W.4: Bondpad Metal1 slot width must be == 1.00
1238 0 BONDPAD.R.1: Minimum Bondpad Via1 inside Metal1 to Metal2 crossing must be >= 16.0
1243 0 BONDPAD.SP.5: Bondpad Metal2 slot to Bondpad Metal2 slot spacing must be == 1.50
1247 0 BONDPAD.W.4: Bondpad Metal2 slot width must be == 1.00
1258 0 BONDPAD.R.1: Minimum Bondpad Via2 inside Metal2 to Metal3 crossing must be >= 16.0
1263 0 BONDPAD.SP.5: Bondpad Metal3 slot to Bondpad Metal3 slot spacing must be == 1.50
1267 0 BONDPAD.W.4: Bondpad Metal3 slot width must be == 1.00
1278 0 BONDPAD.R.1: Minimum Bondpad Via3 inside Metal3 to Metal4 crossing must be >= 16.0
1283 0 BONDPAD.SP.5: Bondpad Metal4 slot to Bondpad Metal4 slot spacing must be == 1.50
1287 0 BONDPAD.W.4: Bondpad Metal4 slot width must be == 1.00
1298 0 BONDPAD.R.1: Minimum Bondpad Via4 inside Metal4 to Metal5 crossing must be >= 16.0
1303 0 BONDPAD.SP.5: Bondpad Metal5 slot to Bondpad Metal5 slot spacing must be == 1.50
1307 0 BONDPAD.W.4: Bondpad Metal5 slot width must be == 1.00
1318 0 BONDPAD.R.1: Minimum Bondpad Via5 inside Metal5 to Metal6 crossing must be >= 16.0
1323 0 BONDPAD.SP.5: Bondpad Metal6 slot to Bondpad Metal6 slot spacing must be == 1.50
1327 0 BONDPAD.W.4: Bondpad Metal6 slot width must be == 1.00
1338 0 BONDPAD.R.1: Minimum Bondpad Via6 inside Metal6 to Metal7 crossing must be >= 16.0
1343 0 BONDPAD.SP.5: Bondpad Metal7 slot to Bondpad Metal7 slot spacing must be == 1.50
1347 0 BONDPAD.W.4: Bondpad Metal7 slot width must be == 1.00
1358 0 BONDPAD.R.1: Minimum Bondpad Via7 inside Metal7 to Metal8 crossing must be >= 16.0
1363 0 BONDPAD.SP.5: Bondpad Metal8 slot to Bondpad Metal8 slot spacing must be == 1.50
1367 0 BONDPAD.W.4: Bondpad Metal8 slot width must be == 1.00
1378 0 BONDPAD.R.1: Minimum Bondpad Via8 inside Metal8 to Metal9 crossing must be >= 16.0
1383 0 BONDPAD.SP.5: Bondpad Metal9 slot to Bondpad Metal9 slot spacing must be == 1.50
1387 0 BONDPAD.W.4: Bondpad Metal9 slot width must be == 1.00
1398 0 BONDPAD.R.2: Minimum Bondpad Via9 inside Metal9 to Metal10 crossing must be >= 4.0
1403 0 BONDPAD.SP.5: Bondpad Metal10 slot to Bondpad Metal10 slot spacing must be == 1.50
1407 0 BONDPAD.W.4: Bondpad Metal10 slot width must be == 1.00
1412 0 BONDPAD.R.2: Minimum Bondpad Via10 inside Metal10 to Metal11 crossing must be >= 4.0
1791 0 OXIDE.L.1_OXIDE.L.2: Maximum Oxide length between two contacts (when the Oxide width is <= 0.18um) must be <= 12.0um and Maximum Oxide length between one contact and the end of the Oxide line (when the Oxide width is <= 0.18um) must be <= 6.0um
1819 0 BONDPAD.W.5: Bondpad Metal1 outside Metal1 ring width must be == 5.00
1847 0 BONDPAD.W.5: Bondpad Metal2 outside Metal2 ring width must be == 5.00
1875 0 BONDPAD.W.5: Bondpad Metal3 outside Metal3 ring width must be == 5.00
1903 0 BONDPAD.W.5: Bondpad Metal4 outside Metal4 ring width must be == 5.00
1931 0 BONDPAD.W.5: Bondpad Metal5 outside Metal5 ring width must be == 5.00
1959 0 BONDPAD.W.5: Bondpad Metal6 outside Metal6 ring width must be == 5.00
1987 0 BONDPAD.W.5: Bondpad Metal7 outside Metal7 ring width must be == 5.00
2015 0 BONDPAD.W.5: Bondpad Metal8 outside Metal8 ring width must be == 5.00
2043 0 BONDPAD.W.5: Bondpad Metal9 outside Metal9 ring width must be == 5.00
2071 0 BONDPAD.W.5: Bondpad Metal10 outside Metal10 ring width must be == 5.00
2090 0 VIA1.X.2: Metal1 must connect to Metal2 with >= 4 Via1 spaced < 0.30 um or >= 9 Via1 spaced < 0.60 um
2109 0 VIA2.X.2: Metal2 must connect to Metal3 with >= 4 Via2 spaced < 0.30 um or >= 9 Via2 spaced < 0.60 um
2128 0 VIA3.X.2: Metal3 must connect to Metal4 with >= 4 Via3 spaced < 0.30 um or >= 9 Via3 spaced < 0.60 um
2147 0 VIA4.X.2: Metal4 must connect to Metal5 with >= 4 Via4 spaced < 0.30 um or >= 9 Via4 spaced < 0.60 um
2166 0 VIA5.X.2: Metal5 must connect to Metal6 with >= 4 Via5 spaced < 0.30 um or >= 9 Via5 spaced < 0.60 um
2185 0 VIA6.X.2: Metal6 must connect to Metal7 with >= 4 Via6 spaced < 0.30 um or >= 9 Via6 spaced < 0.60 um
2204 0 VIA7.X.2: Metal7 must connect to Metal8 with >= 4 Via7 spaced < 0.30 um or >= 9 Via7 spaced < 0.60 um
2223 0 VIA8.X.2: Metal8 must connect to Metal9 with >= 4 Via8 spaced < 0.30 um or >= 9 Via8 spaced < 0.60 um
2243 0 VIA1.X.1: Metal1 must connect to Metal2 with >= 2 Via1 spaced < 0.30 um or >= 4 Via1 spaced < 0.60 um
2263 0 VIA2.X.1: Metal2 must connect to Metal3 with >= 2 Via2 spaced < 0.30 um or >= 4 Via2 spaced < 0.60 um
2283 0 VIA3.X.1: Metal3 must connect to Metal4 with >= 2 Via3 spaced < 0.30 um or >= 4 Via3 spaced < 0.60 um
2303 0 VIA4.X.1: Metal4 must connect to Metal5 with >= 2 Via4 spaced < 0.30 um or >= 4 Via4 spaced < 0.60 um
2323 0 VIA5.X.1: Metal5 must connect to Metal6 with >= 2 Via5 spaced < 0.30 um or >= 4 Via5 spaced < 0.60 um
2343 0 VIA6.X.1: Metal6 must connect to Metal7 with >= 2 Via6 spaced < 0.30 um or >= 4 Via6 spaced < 0.60 um
2363 0 VIA7.X.1: Metal7 must connect to Metal8 with >= 2 Via7 spaced < 0.30 um or >= 4 Via7 spaced < 0.60 um
2383 0 VIA8.X.1: Metal8 must connect to Metal9 with >= 2 Via8 spaced < 0.30 um or >= 4 Via8 spaced < 0.60 um
2389 0 BONDPAD.B.1A: Bondpad Metal1 must have bevelled corners
2395 0 BONDPAD.B.1A: Bondpad Metal2 must have bevelled corners
2401 0 BONDPAD.B.1A: Bondpad Metal3 must have bevelled corners
2407 0 BONDPAD.B.1A: Bondpad Metal4 must have bevelled corners
2413 0 BONDPAD.B.1A: Bondpad Metal5 must have bevelled corners
2419 0 BONDPAD.B.1A: Bondpad Metal6 must have bevelled corners
2425 0 BONDPAD.B.1A: Bondpad Metal7 must have bevelled corners
2431 0 BONDPAD.B.1A: Bondpad Metal8 must have bevelled corners
2437 0 BONDPAD.B.1A: Bondpad Metal9 must have bevelled corners
2443 0 BONDPAD.B.1A: Bondpad Metal10 must have bevelled corners
2449 0 BONDPAD.B.1A: Bondpad Metal11 must have bevelled corners
2451 0 ptap_StampErrorFloat
2452 0 ptap_StampErrorMult
2453 0 ptap_StampErrorConnect
2458 0 psubstrate_StampErrorFloat
2459 0 psubstrate_StampErrorMult
2460 0 psubstrate_StampErrorConnect
2465 0 ntap_StampErrorFloat
2466 0 ntap_StampErrorMult
2467 0 ntap_StampErrorConnect
2472 0 nwell_conn_StampErrorFloat
2473 0 nwell_conn_StampErrorMult
2474 0 nwell_conn_StampErrorConnect
2479 0 nb_tap_StampErrorFloat
2480 0 nb_tap_StampErrorMult
2481 0 nb_tap_StampErrorConnect
2486 0 Nburied_StampErrorFloat
2487 0 Nburied_StampErrorMult
2488 0 Nburied_StampErrorConnect
2526 0 NBL.W.1: Minimum Nburied Width >= 0.8 um
2528 0 NBL.E.1: Minimum Nburied to Nwell enclosure >= 0.2 um
2530 0 NBL.E.1: Minimum Nburied to Nwell enclosure >= 0.2 um
2532 0 NBL.SP.1: Minimum Nburied to Nburied spacing >= 2.0 um
2534 0 NBL.SE.1: Minimum Nburied to non-related Nwell spacing >= 2.2 um
2535 0 NBL.SE.1: Minimum Nburied to non-related Nwell spacing >= 2.2 um
2538 0 NBL.SE.2: Minimum Nburied to non-related Oxide spacing >= 1.2 um
2539 0 NBL.SE.2: Minimum Nburied to non-related Oxide spacing >= 1.2 um
2544 0 NBL.SE.3: Minimum Nwell ring (on Nburied) to P+ Active spacing >= 0.09 um
2546 0 NBL.SE.3: Minimum Nwell ring (on Nburied) to P+ Active spacing >= 0.09 um
2550 0 NBL.SE.4: Minimum Nwell ring (on Nburied) to N+ Active spacing >= 0.09 um
2552 0 NBL.SE.4: Minimum Nwell ring (on Nburied) to N+ Active spacing >= 0.09 um
2554 0 NW.SP.1: Minimum Nwell spacing to Nwell (same potential) >= 0.3 um
2556 0 NW.SP.1: Minimum Nwell spacing to Nwell (same potential) >= 0.3 um
2559 0 NW.SP.2: Minimum Nwell spacing to Nwell (different potential) >= 0.6 um
2560 0 NW.SP.2: Minimum Nwell spacing to Nwell (different potential) >= 0.6 um
2562 0 NW.SP.2: Minimum Nwell spacing to Nwell (different potential) >= 0.6 um
2563 0 NW.W.1: Minimum Nwell Width >= 0.3 um
2565 0 NW.SP.2: Minimum Nwell spacing to Nwell (different potential) >= 0.6 um
2568 0 NW.SE.2: Minimum Nwell spacing to P+ Active Area >= 0.16 um
2569 0 NW.SE.2: Minimum Nwell spacing to P+ Active Area >= 0.16 um
2573 0 NW.SE.1: Minimum Nwell spacing to N+ Active Area >= 0.16 um
2574 0 NW.SE.1: Minimum Nwell spacing to N+ Active Area >= 0.16 um
2579 0 NW.SE.3: Minimum Nwell spacing to N+ 1.8V Active Area >= 0.24 um
2580 0 NW.SE.3: Minimum Nwell spacing to N+ 1.8V Active Area >= 0.24 um
2585 0 NW.SE.4: Minimum Nwell spacing to P+ 1.8V Active Area >= 0.24 um
2586 0 NW.SE.4: Minimum Nwell spacing to P+ 1.8V Active Area >= 0.24 um
2590 0 NW.E.1: Minimum Nwell enclosure of N+ Active Area >= 0.06 um
2592 0 NW.E.1: Minimum Nwell enclosure of N+ Active Area >= 0.06 um
2593 0 NW.E.2: Minimum Nwell enclosure of P+ Active Area >= 0.06 um
2595 0 NW.E.2: Minimum Nwell enclosure of P+ Active Area >= 0.06 um
2596 0 NW.E.3: Minimum Nwell enclosure of N+ 1.8V Active Area >= 0.24 um
2598 0 NW.E.3: Minimum Nwell enclosure of N+ 1.8V Active Area >= 0.24 um
2599 0 NW.E.4: Minimum Nwell enclosure of P+ 1.8V Active Area >= 0.24 um
2601 0 NW.E.4: Minimum Nwell enclosure of P+ 1.8V Active Area >= 0.24 um
2602 0 NW.A.1: Minimum Nwell area >= 0.18 um
2603 0 NW.EA.1: Minimum Nwell enclosed area >= 0.18 um
2604 0 NWR.SE.1: Minimum Resist Protect Oxide to Nwell spacing >= 0.16 um
2606 0 NWR.E.1: Minimum Active Area to Nwell (in resistor) enclosure >= 0.6 um
2608 0 NWR.E.2: Minimum salicided Nwell to Contact enclosure >= 0.16 um
2610 0 NWR.E.2: Minimum salicided Nwell to Contact enclosure >= 0.16 um
2611 0 NWR.X.1: Thick Oxide is NOT allowed over Nwell resistor
2616 0 NWR.O.1: Minimum N+ Implant to Resist Protect Oxide overlap >= 0.22 um
2617 0 OXIDE.W.1: Minimum Active Area width >= 0.05 um
2622 0 OXIDE.W.2.1.1: Minimum 1.1V N-channel gate width >= 0.12 um
2626 0 OXIDE.W.2.1.2: Minimum 1.8V N-channel gate width >= 0.32 um
2631 0 OXIDE.W.2.2.1: Minimum 1.1V P-channel gate width >= 0.12 um
2635 0 OXIDE.W.2.2.2: Minimum 1.8V P-channel gate width >= 0.32 um
2637 0 OXIDE.W.3: Minimum Active Area bent 45 degress width >= 0.06 um
2639 0 OXIDE.SP.1: Minimum N+ Active Area to N+ Active Area spacing >= 0.08 um
2641 0 OXIDE.SP.2: Minimum P+ Active Area to P+ Active Area spacing >= 0.08 um
2646 0 OXIDE.SP.3: Minimum N+ Active Area to P+ Active Area spacing >= 0.1 um
2647 0 OXIDE.SE.1: Minimum Active Area to Thick Active Area spacing >= 0.18 um
2648 0 OXIDE.SP.4: Minimum Active Area bent 45 degress to Active Area spacing >= 0.1 um
2649 0 OXIDE.A.1: Minimum area for Active Area >= 0.035 um
2653 0 OXIDE.EA.1: Minimum Active Area enclosed area >= 0.04 um
2657 0 OXIDE.X.1: Oxide must be covered by N+ Implant or Nzvt or Salicide Block
2660 0 OXIDER.SE.2: Minimum Active Resistor to N+ or P+ Implant spacing >= 0.16 um
2661 0 OXIDER.SE.2: Minimum Active Resistor to N+ or P+ Implant spacing >= 0.16 um
2664 0 OXIDER.SE.2: Minimum Active Resistor to N+ or P+ Implant spacing >= 0.16 um
2665 0 OXIDER.SE.2: Minimum Active Resistor to N+ or P+ Implant spacing >= 0.16 um
2667 0 OXIDER.E.1: Minimum Salicide Block to Active Resistor enclosure >= 0.12 um
2669 0 OXIDER.X.1: Oxide resistors must have N+ or P+ Implant
2670 0 OXIDETHK.W.1: Minimum Thick Active Area width >= 0.35 um
2672 0 OXIDETHK.SP.1: Minimum Thick Active Area to Thick Active Area spacing >= 0.16 um
2674 0 OXIDETHK.SP.2: Minimum Thick Active Area bent 45 degrees to Thick Active Area spacing >= 0.32 um
2676 0 OXIDETHK.SE.1: Minimum N+ 1.8V Active Area to 1.8V N+ Active Area spacing >= 0.1 um
2678 0 OXIDETHK.SE.2: Minimum P+ 1.8V Active Area to 1.8V P+ Active Area spacing >= 0.1 um
2679 0 OXIDETHK.SE.3: Minimum N+ 1.8V Active Area to 1.8V P+ Active Area spacing >= 0.12 um
2681 0 OXIDETHK.E.1: Minimum Thick Active Area to Active Area enclosure >= 0.16 um
2688 0 OXIDETHK.SE.5: Minimum Thick Active Area to 1.1V Poly gate spacing >= 0.18 um
2689 0 OXIDETHK.SE.5: Minimum Thick Active Area to 1.1V Poly gate spacing >= 0.18 um
2691 0 OXIDETHK.E.2: Minimum Thick Active Area to Thick Poly gate enclosure >= 0.18 um
2692 0 NHVT.W.1: Minimum Nhvt width >= 0.12
2694 0 NHVT.SP.1: Minimum Nhvt spacing >= 0.12
2695 0 NHVT.X.2: Nhvt is NOT allowed on Nwell
2696 0 NHVT.X.3: Nhvt is NOT allowed on P+ Oxide
2697 0 NHVT.X.4: Nhvt is NOT allowed on Nzvt
2698 0 PHVT.W.1: Minimum Phvt width >= 0.12
2700 0 PHVT.SP.1: Minimum Phvt spacing >= 0.12
2701 0 PHVT.X.2: Phvt is NOT allowed outside Nwell
2702 0 PHVT.X.3: Phvt is NOT allowed on N+ Oxide
2703 0 PHVT.X.4: Phvt is NOT allowed on Nzvt
2704 0 NLVT.W.1: Minimum Nlvt width >= 0.12
2706 0 NLVT.SP.1: Minimum Nlvt spacing >= 0.12
2707 0 NLVT.X.2: Nlvt is NOT allowed on Nwell
2708 0 NLVT.X.3: Nlvt is NOT allowed on P+ Oxide
2709 0 NLVT.X.4: Nlvt is NOT allowed on Nzvt
2710 0 PLVT.W.1: Minimum Plvt width >= 0.12
2712 0 PLVT.SP.1: Minimum Plvt spacing >= 0.12
2713 0 PLVT.X.2: Plvt is NOT allowed outside Nwell
2714 0 PLVT.X.3: Plvt is NOT allowed on N+ Oxide
2715 0 PLVT.X.4: Plvt is NOT allowed on Nzvt
2716 0 NZVT.W.1: Minimum Nzvt width >= 0.35 um
2718 0 NZVT.SP.1: Minimum Nzvt to Nzvt spacing >= 0.3 um
2721 0 NZVT.SE.1: Minimum Nzvt to Active spacing >= 0.18 um
2722 0 NZVT.SE.1: Minimum Nzvt to Active spacing >= 0.18 um
2723 0 NZVT.SE.2: Minimum Nzvt to Nwell spacing >= 0.6 um
2724 0 NZVT.SE.2: Minimum Nzvt to Nwell spacing >= 0.6 um
2727 0 NZVT.E.1: Minimum N+ Poly gate end cap to Native Active Area enclosure >= 0.1 um
2730 0 NZVT.L.1: Minimum Native device Poly gate length >= 0.30 um
2734 0 NZVT.W.2: Minimum Native device Poly gate width >= 0.50 um
2736 0 NZVT.X.3: P+ Oxide is NOT allowed in Nzvt
2739 0 POLY.W.1: Minimum 1.1V N-channel gate length >= 0.045 um
2742 0 POLY.W.2: Minimum 1.1V P-channel gate length >= 0.045 um
2746 0 POLY.W.3: Minimum 1.8V N-channel gate length >= 0.15 um
2751 0 POLY.W.4: Minimum 1.8V P-channel gate length >= 0.15 um
2754 0 POLY.W.5: Minimum Poly interconnect width >= 0.045 um
2758 0 POLY.SP.1: Minimum Poly resistor space >= 0.3 um
2760 0 POLY.SP.2: Minimum Poly gate space  >= 0.06 um
2762 0 POLY.SP.3: Minimum Poly interconnect space >= 0.06 um
2766 0 POLY.SP.4: Minimum gate space in thick active >= 0.20 um
2769 0 POLY.E.1: Minimum N-channel gate extension beyond Active Area >= 0.1 um
2771 0 POLY.E.1: Minimum N-channel gate extension beyond Active Area >= 0.1 um
2774 0 POLY.E.2: Minimum P-channel gate extension beyond Active Area >= 0.1 um
2776 0 POLY.E.2: Minimum P-channel gate extension beyond Active Area >= 0.1 um
2777 0 POLY.SE.1_POLY.SE.2: Minimum Poly interconnect to related Active Area space >= 0.05 um
2779 0 POLY.E.3: Minimum Active Area (source/drain) to gate enclosure >= 0.1 um
2781 0 POLY.W.6: Minimum bent Poly width >= 0.1 um
2783 0 POLY.SP.5: Minimum bent Poly space >= 0.1 um
2784 0 POLY.X.1: Poly gate cannot have bends
2785 0 POLY.X.2: Poly resistor cannot have bends
4197 0 POLY.LN.1  Maximum Poly length [Poly width is <= 0.16 um] between two contacts as well as between one contact and the Poly line end <= 20um  
4198 0 POLY.A.1: Minimum area for Poly interconnect >= 0.02 um
4202 0 POLY.EA.1: Minimum enclosed area for Poly interconnect >= 0.05 um
4204 0 POLYR.E.1: Minimum Salicide Block to Poly resistor enclosure >= 0.14 um
4206 0 POLYR.E.2: Minimum N+ Implant to Poly used in resistor enclosure >= 0.07 um
4208 0 POLYR.E.2: Minimum N+ Implant to Poly used in resistor enclosure >= 0.07 um
4210 0 POLYR.E.3: Minimum P+ Implant to Poly used in resistor enclosure >= 0.07 um
4212 0 POLYR.E.3: Minimum P+ Implant to Poly used in resistor enclosure >= 0.07 um
4214 0 POLYR.SE.2: Minimum Poly resistor to other Implant spacing >= 0.15 um
4215 0 POLYR.SE.2: Minimum Poly resistor to other Implant spacing >= 0.15 um
4216 0 POLYR.SE.2: Minimum Poly resistor to other Implant spacing >= 0.15 um
4217 0 POLYR.SE.2: Minimum Poly resistor to other Implant spacing >= 0.15 um
4219 0 POLYR.SE.2: Minimum Poly resistor to other Implant spacing >= 0.15 um
4220 0 POLYR.SE.2: Minimum Poly resistor to other Implant spacing >= 0.15 um
4221 0 POLYR.X.1: Poly resistors must have N+ or P+ Implant
4222 0 NIMP.W.1: Minimum N+ Implant width >= 0.12 um
4224 0 NIMP.SP.1: Minimum N+ Implant space >= 0.12 um
4227 0 NIMP.E.1: Minimum N+ Implant to Active Area enclosure >= 0.07 um
4228 0 NIMP.O.1: Minimum N+ Implant to Active Area overlap >= 0.08 um
4236 0 NIMP.SE.1: Minimum N+ Implant to P+ Active Area (inside Nwell) spacing >= 0.08 um
4237 0 NIMP.SE.1: Minimum N+ Implant to P+ Active Area (inside Nwell) spacing >= 0.08 um
4240 0 NIMP.E.2: Minimum N+ Implant to Active Area (Nwell tie) enclosure >= 0.01 um
4244 0 NIMP.E.3: Minimum N+ Implant to gate side enclosure >= 0.1 um
4250 0 NIMP.E.4: Minimum N+ Implant to gate (endcap) enclosure >= 0.1 um
4252 0 NIMP.E.4: Minimum N+ Implant to gate (endcap) enclosure >= 0.1 um
4261 0 NIMP.SE.2: Minimum N+ Implant to P+ Active Area (substrate tie) spacing >= 0.02 um
4262 0 NIMP.SE.2: Minimum N+ Implant to P+ Active Area (substrate tie) spacing >= 0.02 um
4263 0 NIMP.A.1: Minimum area for N+ Implant >= 0.018 um
4267 0 NIMP.EA.1: Minimum N+ Implant ring enclosed area  >= 0.04 um
4270 0 NIMP.SE.3: Minimum N+ Implant to P+ gate side (butted Implant) spacing >= 0.1 um
4271 0 NIMP.SE.3: Minimum N+ Implant to P+ gate side (butted Implant) spacing >= 0.1 um
4272 0 NIMP.X.1: Nimp is NOT allowed over Pimp
4273 0 PIMP.W.1: Minimum P+ Implant width >= 0.12 um
4275 0 PIMP.SP.1: Minimum P+ Implant space >= 0.12 um
4277 0 PIMP.E.1: Minimum P+ Implant to Active Area enclosure >= 0.07 um
4278 0 PIMP.O.1: Minimum P+ Implant to Active Area overlap >= 0.08 um
4286 0 PIMP.SE.1: Minimum P+ Implant to N+ Active Area (outside Nwell) spacing >= 0.08 um
4287 0 PIMP.SE.1: Minimum P+ Implant to N+ Active Area (outside Nwell) spacing >= 0.08 um
4289 0 PIMP.E.2: Minimum P+ Implant to Active Area (substrate tie) enclosure >= 0.01 um
4293 0 PIMP.E.3: Minimum P+ Implant to gate side enclosure >= 0.1 um
4296 0 PIMP.E.4: Minimum P+ Implant to gate (endcap) enclosure >= 0.1 um
4298 0 PIMP.E.4: Minimum P+ Implant to gate (endcap) enclosure >= 0.1 um
4307 0 PIMP.SE.2: Minimum P+ Implant to N+ Active Area (Nwell tie) spacing >= 0.02 um
4308 0 PIMP.SE.2: Minimum P+ Implant to N+ Active Area (Nwell tie) spacing >= 0.02 um
4309 0 PIMP.A.1: Minimum area for P+ Implant >= 0.018 um
4313 0 PIMP.EA.1: Minimum P+ Implant ring enclosed area  >= 0.04 um
4316 0 PIMP.SE.3: Minimum P+ Implant to N+ gate side (butted Implant) spacing >= 0.1 um
4317 0 PIMP.SE.3: Minimum P+ Implant to N+ gate side (butted Implant) spacing >= 0.1 um
4319 0 CONT.W.1: Maximum and minimum Contact width/length == 0.06 um
4321 0 CONT.SP.1: Minimum Contact to Contact spacing >= 0.06 um
4323 0 CONT.SP.2: Space to three adjacent Contacts ( < 0.10um apart) >= 0.08 um
4326 0 CONT.SE.1: Minimum Contact on Active Area to gate spacing >= 0.05 um
4327 0 CONT.SE.1: Minimum Contact on Active Area to gate spacing >= 0.05 um
4331 0 CONT.SE.2: Minimum Contact on 1.8V Active Area to gate spacing >= 0.06 um
4332 0 CONT.SE.2: Minimum Contact on 1.8V Active Area to gate spacing >= 0.06 um
4334 0 CONT.SE.3: Minimum gate Contact on Active Area spacing >= 0.06 um
4335 0 CONT.SE.3: Minimum gate Contact on Active Area spacing >= 0.06 um
4340 0 CONT.SE.4: Minimum 1.8V gate Contact on Active Area spacing >= 0.07 um
4341 0 CONT.SE.4: Minimum 1.8V gate Contact on Active Area spacing >= 0.07 um
4343 0 CONT.E.1: Minimum Active Area to Contact enclosure >= 0.03 um
4345 0 CONT.E.1: Minimum Active Area to Contact enclosure >= 0.03 um
4347 0 CONT.E.2: Minimum Poly to Contact enclosure >= 0.02 um
4349 0 CONT.E.2: Minimum Poly to Contact enclosure >= 0.02 um
4352 0 CONT.E.3: Minimum Poly to Contact enclosure on at least two opposite sides >= 0.03 um
4355 0 CONT.E.4: Minimum N+/P+ Implant on Active Area to Contact enclosure >= 0.03 um
4357 0 CONT.E.4: Minimum N+/P+ Implant on Active Area to Contact enclosure >= 0.03 um
4360 0 CONT.E.4: Minimum N+/P+ Implant on Active Area to Contact enclosure >= 0.03 um
4362 0 CONT.E.4: Minimum N+/P+ Implant on Active Area to Contact enclosure >= 0.03 um
4363 0 CONT.X.1: Cont on gate is NOT allowed
4366 0 CONT.X.2: Nimp edge is NOT allowed on Oxide Cont
4369 0 CONT.X.2: Pimp edge is NOT allowed on Oxide Cont
4370 0 CONT.X.3: CONT must be covered by Oxide or Poly
4371 0 SIPROT.W.1: Minimum Salicide Block width >= 0.22 um
4373 0 SIPROT.SP.1: Minimum Salicide Block space >= 0.22 um
4376 0 SIPROT.SE.1: Minimum Salicide Block to Contact spacing >= 0.12 um
4377 0 SIPROT.SE.1: Minimum Salicide Block to Contact spacing >= 0.12 um
4378 0 SIPROT.SE.2: Minimum Salicide Block to unrelated Active Area spacing >= 0.12 um
4382 0 SIPROT.SE.3: Minimum Salicide Block to gate spacing >= 0.22 um
4383 0 SIPROT.SE.3: Minimum Salicide Block to gate spacing >= 0.22 um
4385 0 SIPROT.E.2: Minimum Active Area to Salicide Block enclosure >= 0.12 um
4389 0 SIPROT.E.1: Minimum Salicide Block to Active Area enclosure >= 0.12 um
4391 0 SIPROT.E.3: Minimum Salicide Block to Poly (on field) enclosure >= 0.14 um
4392 0 SIPROT.A.1: Minimum Salicide Block area >= 0.6 um
4393 0 SIPROT.SE.4: Minimum Salicide Block to Poly (on field) spacing >= 0.18 um
4397 0 SIPROT.EA.1: Minimum Salicide Block enclosed area >= 0.6 um
4398 0 METAL2.E.1: Metal2 to Via1 enclosure must be >= 0.005 um
4400 0 METAL2.E.1: Metal2 to Via1 enclosure must be >= 0.005 um
4404 0 METAL2.E.2: Metal2 to Via1 enclosure on opposite sides must be >= 0.03 um
4405 0 METAL3.E.1: Metal3 to Via2 enclosure must be >= 0.005 um
4407 0 METAL3.E.1: Metal3 to Via2 enclosure must be >= 0.005 um
4411 0 METAL3.E.2: Metal3 to Via2 enclosure on opposite sides must be >= 0.03 um
4412 0 METAL4.E.1: Metal4 to Via3 enclosure must be >= 0.005 um
4414 0 METAL4.E.1: Metal4 to Via3 enclosure must be >= 0.005 um
4418 0 METAL4.E.2: Metal4 to Via3 enclosure on opposite sides must be >= 0.03 um
4419 0 METAL5.E.1: Metal5 to Via4 enclosure must be >= 0.005 um
4421 0 METAL5.E.1: Metal5 to Via4 enclosure must be >= 0.005 um
4425 0 METAL5.E.2: Metal5 to Via4 enclosure on opposite sides must be >= 0.03 um
4426 0 METAL6.E.1: Metal6 to Via5 enclosure must be >= 0.005 um
4428 0 METAL6.E.1: Metal6 to Via5 enclosure must be >= 0.005 um
4432 0 METAL6.E.2: Metal6 to Via5 enclosure on opposite sides must be >= 0.03 um
4433 0 METAL7.E.1: Metal7 to Via6 enclosure must be >= 0.005 um
4435 0 METAL7.E.1: Metal7 to Via6 enclosure must be >= 0.005 um
4439 0 METAL7.E.2: Metal7 to Via6 enclosure on opposite sides must be >= 0.03 um
4440 0 METAL8.E.1: Metal8 to Via7 enclosure must be >= 0.005 um
4442 0 METAL8.E.1: Metal8 to Via7 enclosure must be >= 0.005 um
4446 0 METAL8.E.2: Metal8 to Via7 enclosure on opposite sides must be >= 0.03 um
4447 0 METAL9.E.1: Metal9 to Via8 enclosure must be >= 0.005 um
4449 0 METAL9.E.1: Metal9 to Via8 enclosure must be >= 0.005 um
4453 0 METAL9.E.2: Metal9 to Via8 enclosure on opposite sides must be >= 0.03 um
4454 0 METAL10.E.1: Metal10 to Via9 enclosure must be >= 0.03 um
4456 0 METAL10.E.1: Metal10 to Via9 enclosure must be >= 0.03 um
4460 0 METAL10.E.2: Metal10 to Via9 enclosure on opposite sides must be >= 0.05 um
4461 0 METAL11.E.1: Metal11 to Via10 enclosure must be >= 0.03 um
4463 0 METAL11.E.1: Metal11 to Via10 enclosure must be >= 0.03 um
4467 0 METAL11.E.2: Metal11 to Via10 enclosure on opposite sides must be >= 0.05 um
4468 0 METAL1.E.1: 0.00 >= 0.00 um
4472 0 METAL1.E.2: 0.03 >= 0.03 um
4473 0 METAL1.W.1: Metal1 width must be >= 0.06 um
4474 0 METAL2.W.1: Metal2 width must be >= 0.08 um
4475 0 METAL3.W.1: Metal3 width must be >= 0.08 um
4476 0 METAL4.W.1: Metal4 width must be >= 0.08 um
4477 0 METAL5.W.1: Metal5 width must be >= 0.08 um
4478 0 METAL6.W.1: Metal6 width must be >= 0.08 um
4479 0 METAL7.W.1: Metal7 width must be >= 0.08 um
4480 0 METAL8.W.1: Metal8 width must be >= 0.08 um
4481 0 METAL9.W.1: Metal9 width must be >= 0.08 um
4482 0 METAL10.W.1: Metal10 width must be >= 0.22 um
4483 0 METAL11.W.1: Metal11 width must be >= 0.22 um
4487 0 METAL1.W.2: Metal1 width must be <= 6.0 um
4491 0 METAL2.W.2: Metal2 width must be <= 6.0 um
4495 0 METAL3.W.2: Metal3 width must be <= 6.0 um
4499 0 METAL4.W.2: Metal4 width must be <= 6.0 um
4503 0 METAL5.W.2: Metal5 width must be <= 6.0 um
4507 0 METAL6.W.2: Metal6 width must be <= 6.0 um
4511 0 METAL7.W.2: Metal7 width must be <= 6.0 um
4515 0 METAL8.W.2: Metal8 width must be <= 6.0 um
4517 0 METAL9.W.2: Metal9 width must be <= 6.0 um
4519 0 METAL10.W.2: Metal10 width must be <= 6.0 um
4521 0 METAL11.W.2: Metal11 width must be <= 6.0 um
4523 0 METAL1.SP.1.1: Metal1 to Metal1 spacing must be >= 0.06 um
4525 0 METAL2.SP.1.1: Metal2 to Metal2 spacing must be >= 0.07 um
4527 0 METAL3.SP.1.1: Metal3 to Metal3 spacing must be >= 0.07 um
4529 0 METAL4.SP.1.1: Metal4 to Metal4 spacing must be >= 0.07 um
4531 0 METAL5.SP.1.1: Metal5 to Metal5 spacing must be >= 0.07 um
4533 0 METAL6.SP.1.1: Metal6 to Metal6 spacing must be >= 0.07 um
4535 0 METAL7.SP.1.1: Metal7 to Metal7 spacing must be >= 0.07 um
4537 0 METAL8.SP.1.1: Metal8 to Metal8 spacing must be >= 0.07 um
4539 0 METAL9.SP.1.1: Metal9 to Metal9 spacing must be >= 0.07 um
4541 0 METAL10.SP.1.1: Metal10 to Metal10 spacing must be >= 0.20 um
4543 0 METAL11.SP.1.1: Metal11 to Metal11 spacing must be >= 0.20 um
4550 0 METAL1.SP.1.2: Metal1 to Metal1 spacing must be >= 0.1 um
4557 0 METAL2.SP.1.2: Metal2 to Metal2 spacing must be >= 0.15 um
4564 0 METAL3.SP.1.2: Metal3 to Metal3 spacing must be >= 0.15 um
4571 0 METAL4.SP.1.2: Metal4 to Metal4 spacing must be >= 0.15 um
4578 0 METAL5.SP.1.2: Metal5 to Metal5 spacing must be >= 0.15 um
4585 0 METAL6.SP.1.2: Metal6 to Metal6 spacing must be >= 0.15 um
4592 0 METAL7.SP.1.2: Metal7 to Metal7 spacing must be >= 0.15 um
4599 0 METAL8.SP.1.2: Metal8 to Metal8 spacing must be >= 0.15 um
4606 0 METAL9.SP.1.2: Metal9 to Metal9 spacing must be >= 0.15 um
4612 0 METAL1.SP.1.3: Metal1 to Metal1 spacing must be >= 0.25 um
4618 0 METAL2.SP.1.3: Metal2 to Metal2 spacing must be >= 0.25 um
4624 0 METAL3.SP.1.3: Metal3 to Metal3 spacing must be >= 0.25 um
4630 0 METAL4.SP.1.3: Metal4 to Metal4 spacing must be >= 0.25 um
4636 0 METAL5.SP.1.3: Metal5 to Metal5 spacing must be >= 0.25 um
4642 0 METAL6.SP.1.3: Metal6 to Metal6 spacing must be >= 0.25 um
4648 0 METAL7.SP.1.3: Metal7 to Metal7 spacing must be >= 0.25 um
4654 0 METAL8.SP.1.3: Metal8 to Metal8 spacing must be >= 0.25 um
4660 0 METAL9.SP.1.3: Metal9 to Metal9 spacing must be >= 0.25 um
4667 0 METAL10.SP.1.2: Metal10 to Metal10 spacing must be >= 0.35 um
4674 0 METAL11.SP.1.2: Metal11 to Metal11 spacing must be >= 0.35 um
4680 0 METAL1.SP.1.4: Metal1 to Metal1 spacing must be >= 0.45 um
4686 0 METAL2.SP.1.4: Metal2 to Metal2 spacing must be >= 0.45 um
4692 0 METAL3.SP.1.4: Metal3 to Metal3 spacing must be >= 0.45 um
4698 0 METAL4.SP.1.4: Metal4 to Metal4 spacing must be >= 0.45 um
4704 0 METAL5.SP.1.4: Metal5 to Metal5 spacing must be >= 0.45 um
4710 0 METAL6.SP.1.4: Metal6 to Metal6 spacing must be >= 0.45 um
4716 0 METAL7.SP.1.4: Metal7 to Metal7 spacing must be >= 0.45 um
4722 0 METAL8.SP.1.4: Metal8 to Metal8 spacing must be >= 0.45 um
4728 0 METAL9.SP.1.4: Metal9 to Metal9 spacing must be >= 0.45 um
4734 0 METAL10.SP.1.3: Metal10 to Metal10 spacing must be >= 0.45 um
4740 0 METAL11.SP.1.3: Metal11 to Metal11 spacing must be >= 0.45 um
4746 0 METAL1.SP.1.5: Metal1 to Metal1 spacing must be >= 0.75 um
4752 0 METAL2.SP.1.5: Metal2 to Metal2 spacing must be >= 0.75 um
4758 0 METAL3.SP.1.5: Metal3 to Metal3 spacing must be >= 0.75 um
4764 0 METAL4.SP.1.5: Metal4 to Metal4 spacing must be >= 0.75 um
4770 0 METAL5.SP.1.5: Metal5 to Metal5 spacing must be >= 0.75 um
4776 0 METAL6.SP.1.5: Metal6 to Metal6 spacing must be >= 0.75 um
4782 0 METAL7.SP.1.5: Metal7 to Metal7 spacing must be >= 0.75 um
4788 0 METAL8.SP.1.5: Metal8 to Metal8 spacing must be >= 0.75 um
4794 0 METAL9.SP.1.5: Metal9 to Metal9 spacing must be >= 0.75 um
4800 0 METAL10.SP.1.4: Metal10 to Metal10 spacing must be >= 0.75 um
4806 0 METAL11.SP.1.4: Metal11 to Metal11 spacing must be >= 0.75 um
4810 0 METAL1.SP.1.6: Metal1 to Metal1 spacing must be >= 1.25 um
4814 0 METAL2.SP.1.6: Metal2 to Metal2 spacing must be >= 1.25 um
4818 0 METAL3.SP.1.6: Metal3 to Metal3 spacing must be >= 1.25 um
4822 0 METAL4.SP.1.6: Metal4 to Metal4 spacing must be >= 1.25 um
4826 0 METAL5.SP.1.6: Metal5 to Metal5 spacing must be >= 1.25 um
4830 0 METAL6.SP.1.6: Metal6 to Metal6 spacing must be >= 1.25 um
4834 0 METAL7.SP.1.6: Metal7 to Metal7 spacing must be >= 1.25 um
4838 0 METAL8.SP.1.6: Metal8 to Metal8 spacing must be >= 1.25 um
4842 0 METAL9.SP.1.6: Metal9 to Metal9 spacing must be >= 1.25 um
4846 0 METAL10.SP.1.5: Metal10 to Metal10 spacing must be >= 1.25 um
4850 0 METAL11.SP.1.5: Metal11 to Metal11 spacing must be >= 1.25 um
4852 0 METAL1.L.1: Metal1 non-90 degree segments must be >= 0.1 um
4854 0 METAL2.L.1: Metal2 non-90 degree segments must be >= 0.1 um
4856 0 METAL3.L.1: Metal3 non-90 degree segments must be >= 0.1 um
4858 0 METAL4.L.1: Metal4 non-90 degree segments must be >= 0.1 um
4860 0 METAL5.L.1: Metal5 non-90 degree segments must be >= 0.1 um
4862 0 METAL6.L.1: Metal6 non-90 degree segments must be >= 0.1 um
4864 0 METAL7.L.1: Metal7 non-90 degree segments must be >= 0.1 um
4866 0 METAL8.L.1: Metal8 non-90 degree segments must be >= 0.1 um
4868 0 METAL9.L.1: Metal9 non-90 degree segments must be >= 0.1 um
4869 0 METAL1.SP.2: Metal1 to bent Metal1 spacing must be >= 0.1 um
4870 0 METAL1.W.3: Bent Metal1 (45 degree angle) width must be >= 0.07
4871 0 METAL2.SP.2: Metal2 to bent Metal2 spacing must be >= 0.1 um
4872 0 METAL2.W.3: Bent Metal2 (45 degree angle) width must be >= 0.09
4873 0 METAL3.SP.2: Metal3 to bent Metal3 spacing must be >= 0.1 um
4874 0 METAL3.W.3: Bent Metal3 (45 degree angle) width must be >= 0.09
4875 0 METAL4.SP.2: Metal4 to bent Metal4 spacing must be >= 0.1 um
4876 0 METAL4.W.3: Bent Metal4 (45 degree angle) width must be >= 0.09
4877 0 METAL5.SP.2: Metal5 to bent Metal5 spacing must be >= 0.1 um
4878 0 METAL5.W.3: Bent Metal5 (45 degree angle) width must be >= 0.09
4879 0 METAL6.SP.2: Metal6 to bent Metal6 spacing must be >= 0.1 um
4880 0 METAL6.W.3: Bent Metal6 (45 degree angle) width must be >= 0.09
4881 0 METAL7.SP.2: Metal7 to bent Metal7 spacing must be >= 0.1 um
4882 0 METAL7.W.3: Bent Metal7 (45 degree angle) width must be >= 0.09
4883 0 METAL8.SP.2: Metal8 to bent Metal8 spacing must be >= 0.1 um
4884 0 METAL8.W.3: Bent Metal8 (45 degree angle) width must be >= 0.09
4885 0 METAL9.SP.2: Metal9 to bent Metal9 spacing must be >= 0.1 um
4886 0 METAL9.W.3: Bent Metal9 (45 degree angle) width must be >= 0.09
4887 0 METAL1.SP.3: Min End of Line Spacing >= 0.08
4888 0 METAL2.SP.3: Min End of Line Spacing >= 0.08
4889 0 METAL3.SP.3: Min End of Line Spacing >= 0.08
4890 0 METAL4.SP.3: Min End of Line Spacing >= 0.08
4891 0 METAL5.SP.3: Min End of Line Spacing >= 0.08
4892 0 METAL6.SP.3: Min End of Line Spacing >= 0.08
4893 0 METAL7.SP.3: Min End of Line Spacing >= 0.08
4894 0 METAL8.SP.3: Min End of Line Spacing >= 0.08
4895 0 METAL9.SP.3: Min End of Line Spacing >= 0.08
4896 0 METAL1.A.1: Metal1 area must be >= 0.02 um
4897 0 METAL2.A.1: Metal2 area must be >= 0.02 um
4898 0 METAL3.A.1: Metal3 area must be >= 0.02 um
4899 0 METAL4.A.1: Metal4 area must be >= 0.02 um
4900 0 METAL5.A.1: Metal5 area must be >= 0.02 um
4901 0 METAL6.A.1: Metal6 area must be >= 0.02 um
4902 0 METAL7.A.1: Metal7 area must be >= 0.02 um
4903 0 METAL8.A.1: Metal8 area must be >= 0.02 um
4904 0 METAL9.A.1: Metal9 area must be >= 0.02 um
4905 0 METAL10.A.1: Metal10 area must be >= 0.10 um
4906 0 METAL11.A.1: Metal11 area must be >= 0.10 um
4910 0 METAL1.EA.1: Metal1 enclosed area must be >= 0.05 um
4914 0 METAL2.EA.1: Metal2 enclosed area must be >= 0.05 um
4918 0 METAL3.EA.1: Metal3 enclosed area must be >= 0.05 um
4922 0 METAL4.EA.1: Metal4 enclosed area must be >= 0.05 um
4926 0 METAL5.EA.1: Metal5 enclosed area must be >= 0.05 um
4930 0 METAL6.EA.1: Metal6 enclosed area must be >= 0.05 um
4934 0 METAL7.EA.1: Metal7 enclosed area must be >= 0.05 um
4938 0 METAL8.EA.1: Metal8 enclosed area must be >= 0.05 um
4942 0 METAL9.EA.1: Metal9 enclosed area must be >= 0.05 um
4946 0 METAL10.EA.1: Metal10 enclosed area must be >= 0.05 um
4950 0 METAL11.EA.1: Metal11 enclosed area must be >= 0.05 um
4952 0 CMET.S.1: Minimum space of CapMetal >= 1.0 um
4953 0 CMET.W.1: Minimum width of CapMetal >= 1.0 um
4955 0 CMET.E.1: Minimum Metal 1 overlap of Via 10 on CapMetal >= 0.05 um
4957 0 CMET.E.1: Minimum Metal 1 overlap of Via 10 on CapMetal >= 0.05 um
4959 0 CMET.E.2: Minimum CapMetal overlap of Via 10 >= 0.15 um
4961 0 CMET.E.2: Minimum CapMetal overlap of Via 10 >= 0.15 um
4963 0 CMET.E.4: Minimum Metal 10 overlap of CapMetal >= 0.2 um
4965 0 CMET.E.4: Minimum Metal 10 overlap of CapMetal >= 0.2 um
4967 0 CMET.E.3: Minimum CapMetal extension over Metal 11 >= 0.1 um
4969 0 VIA1.W.1: Via1 shapes must be 0.07x0.07 rectangles
4971 0 VIA1.SP.1: Via1 to Via1 spacing must be >= 0.07 um
4973 0 VIA2.W.1: Via2 shapes must be 0.07x0.07 rectangles
4975 0 VIA2.SP.1: Via2 to Via2 spacing must be >= 0.07 um
4977 0 VIA3.W.1: Via3 shapes must be 0.07x0.07 rectangles
4979 0 VIA3.SP.1: Via3 to Via3 spacing must be >= 0.07 um
4981 0 VIA4.W.1: Via4 shapes must be 0.07x0.07 rectangles
4983 0 VIA4.SP.1: Via4 to Via4 spacing must be >= 0.07 um
4985 0 VIA5.W.1: Via5 shapes must be 0.07x0.07 rectangles
4987 0 VIA5.SP.1: Via5 to Via5 spacing must be >= 0.07 um
4989 0 VIA6.W.1: Via6 shapes must be 0.07x0.07 rectangles
4991 0 VIA6.SP.1: Via6 to Via6 spacing must be >= 0.07 um
4993 0 VIA7.W.1: Via7 shapes must be 0.07x0.07 rectangles
4995 0 VIA7.SP.1: Via7 to Via7 spacing must be >= 0.07 um
4997 0 VIA8.W.1: Via8 shapes must be 0.07x0.07 rectangles
4999 0 VIA8.SP.1: Via8 to Via8 spacing must be >= 0.07 um
5001 0 VIA9.W.1: Via9 shapes must be 0.18x0.18 rectangles
5003 0 VIA9.SP.1: Via9 to Via9 spacing must be >= 0.18 um
5005 0 VIA10.W.1: Via10 shapes must be 0.18x0.18 rectangles
5007 0 VIA10.SP.1: Via10 to Via10 spacing must be >= 0.18 um
5008 0 VIA1.E.1: Metal1 to Via1 enclosure must be >= 0.005 um
5010 0 VIA1.E.1: Metal1 to Via1 enclosure must be >= 0.005 um
5014 0 VIA1.E.2: Metal1 to Via1 enclosure on opposite sides must be >= 0.03 um
5015 0 VIA2.E.1: Metal2 to Via2 enclosure must be >= 0.005 um
5017 0 VIA2.E.1: Metal2 to Via2 enclosure must be >= 0.005 um
5021 0 VIA2.E.2: Metal2 to Via2 enclosure on opposite sides must be >= 0.03 um
5022 0 VIA3.E.1: Metal3 to Via3 enclosure must be >= 0.005 um
5024 0 VIA3.E.1: Metal3 to Via3 enclosure must be >= 0.005 um
5028 0 VIA3.E.2: Metal3 to Via3 enclosure on opposite sides must be >= 0.03 um
5029 0 VIA4.E.1: Metal4 to Via4 enclosure must be >= 0.005 um
5031 0 VIA4.E.1: Metal4 to Via4 enclosure must be >= 0.005 um
5035 0 VIA4.E.2: Metal4 to Via4 enclosure on opposite sides must be >= 0.03 um
5036 0 VIA5.E.1: Metal5 to Via5 enclosure must be >= 0.005 um
5038 0 VIA5.E.1: Metal5 to Via5 enclosure must be >= 0.005 um
5042 0 VIA5.E.2: Metal5 to Via5 enclosure on opposite sides must be >= 0.03 um
5043 0 VIA6.E.1: Metal6 to Via6 enclosure must be >= 0.005 um
5045 0 VIA6.E.1: Metal6 to Via6 enclosure must be >= 0.005 um
5049 0 VIA6.E.2: Metal6 to Via6 enclosure on opposite sides must be >= 0.03 um
5050 0 VIA7.E.1: Metal7 to Via7 enclosure must be >= 0.005 um
5052 0 VIA7.E.1: Metal7 to Via7 enclosure must be >= 0.005 um
5056 0 VIA7.E.2: Metal7 to Via7 enclosure on opposite sides must be >= 0.03 um
5057 0 VIA8.E.1: Metal8 to Via8 enclosure must be >= 0.005 um
5059 0 VIA8.E.1: Metal8 to Via8 enclosure must be >= 0.005 um
5063 0 VIA8.E.2: Metal8 to Via8 enclosure on opposite sides must be >= 0.03 um
5064 0 VIA9.E.1: Metal9 to Via9 enclosure must be >= 0.015 um
5066 0 VIA9.E.1: Metal9 to Via9 enclosure must be >= 0.015 um
5070 0 VIA9.E.2: Metal9 to Via9 enclosure on opposite sides must be >= 0.04 um
5071 0 VIA10.E.1: Metal10 to Via10 enclosure must be >= 0.015 um
5073 0 VIA10.E.1: Metal10 to Via10 enclosure must be >= 0.015 um
5077 0 VIA10.E.2: Metal10 to Via10 enclosure on opposite sides must be >= 0.04 um
5294 0 LATCHUP.1: The maximum distance from any point in a P+ source/drain Active Area to the nearest Nwell pick-up in the same Nwell >= 20.0 um
5893 0 LATCHUP.2: The maximum distance from any point in a N+ source/drain Active Area to the nearest Psub pick-up in the same Psub >= 20.0 um
5896 0 LATCHUP.3: Minimum I/O or ESD NMOS to PMOS spacing >= 10.0 um
5897 0 LATCHUP.3: Minimum I/O or ESD NMOS to PMOS spacing >= 10.0 um
5902 0 LATCHUP.4: Minimum I/O or ESD NMOS to PMOS spacing when not blocked by a double guardring >= 30.0 um
5906 0 LATCHUP.4: Minimum I/O or ESD NMOS to PMOS spacing when not blocked by a double guardring >= 30.0 um
5910 0 ESD.1: ESD gate width must be >= 10.0 um and <= 30.0 um
5911 0 ESD.4: N+ source should connect to Pad or Bulk
5912 0 ESD.4: P+ source should connect to Pad or Nwell
5913 0 ESD.5: NMOS I/O and ESD devices must be inside P+ rings
5914 0 ESD.6: PMOS I/O and ESD devices must be inside N+ rings
5915 0 ESD.7: P+ taps can NOT butt NMOS I/O and ESD devices
5916 0 ESD.7: N+ taps can NOT butt PMOS I/O and ESD devices
5917 0 ESD.8: N+ drains must be non-salicided (except Contact area)
5918 0 ESD.8: P+ drains must be non-salicided (except Contact area)
5921 0 ESD.11: Minimum SiProt to Poly gate overlap in NMOS and PMOS drains >= 0.05 um
5923 0 ESD.12: Minimum enclosure of SiProt edge to Poly gate edge in NMOS and PMOS drains >= 0.9 um
5925 0 ESD.13: Minimum SiProt to Oxide overlap in NMOS and PMOS I/O drains >= 0.9 um
5929 0 ESD.14: Exact gate length of NMOS and PMOS in I/O buffers and in Vdd to Vss ESD protection == 0.2 um
5933 0 ESD.15: Minimu Poly gate to Contact spacing in NMOS and PMOS in I/O buffers and in Vdd to Vss ESD protection >= 0.12 um
5934 0 ESD.15: Minimu Poly gate to Contact spacing in NMOS and PMOS in I/O buffers and in Vdd to Vss ESD protection >= 0.12 um
5936 0 BONDPAD.E.1: Metal1 to Bondpad enclosure must be >= 2.0 um
5938 0 BONDPAD.E.1: Metal1 to Bondpad enclosure must be >= 2.0 um
5939 0 BONDPAD.SP.2: Bondpad Metal1 to Metal1 spacing must be >= 3.0 um
5941 0 BONDPAD.E.1: Metal2 to Bondpad enclosure must be >= 2.0 um
5943 0 BONDPAD.E.1: Metal2 to Bondpad enclosure must be >= 2.0 um
5944 0 BONDPAD.SP.2: Bondpad Metal2 to Metal2 spacing must be >= 3.0 um
5946 0 BONDPAD.E.1: Metal3 to Bondpad enclosure must be >= 2.0 um
5948 0 BONDPAD.E.1: Metal3 to Bondpad enclosure must be >= 2.0 um
5949 0 BONDPAD.SP.2: Bondpad Metal3 to Metal3 spacing must be >= 3.0 um
5951 0 BONDPAD.E.1: Metal4 to Bondpad enclosure must be >= 2.0 um
5953 0 BONDPAD.E.1: Metal4 to Bondpad enclosure must be >= 2.0 um
5954 0 BONDPAD.SP.2: Bondpad Metal4 to Metal4 spacing must be >= 3.0 um
5956 0 BONDPAD.E.1: Metal5 to Bondpad enclosure must be >= 2.0 um
5958 0 BONDPAD.E.1: Metal5 to Bondpad enclosure must be >= 2.0 um
5959 0 BONDPAD.SP.2: Bondpad Metal5 to Metal5 spacing must be >= 3.0 um
5961 0 BONDPAD.E.1: Metal6 to Bondpad enclosure must be >= 2.0 um
5963 0 BONDPAD.E.1: Metal6 to Bondpad enclosure must be >= 2.0 um
5964 0 BONDPAD.SP.2: Bondpad Metal6 to Metal6 spacing must be >= 3.0 um
5966 0 BONDPAD.E.1: Metal7 to Bondpad enclosure must be >= 2.0 um
5968 0 BONDPAD.E.1: Metal7 to Bondpad enclosure must be >= 2.0 um
5969 0 BONDPAD.SP.2: Bondpad Metal7 to Metal7 spacing must be >= 3.0 um
5971 0 BONDPAD.E.1: Metal8 to Bondpad enclosure must be >= 2.0 um
5973 0 BONDPAD.E.1: Metal8 to Bondpad enclosure must be >= 2.0 um
5974 0 BONDPAD.SP.2: Bondpad Metal8 to Metal8 spacing must be >= 3.0 um
5976 0 BONDPAD.E.1: Metal9 to Bondpad enclosure must be >= 2.0 um
5978 0 BONDPAD.E.1: Metal9 to Bondpad enclosure must be >= 2.0 um
5979 0 BONDPAD.SP.2: Bondpad Metal9 to Metal9 spacing must be >= 3.0 um
5981 0 BONDPAD.E.1: Metal10 to Bondpad enclosure must be >= 2.0 um
5983 0 BONDPAD.E.1: Metal10 to Bondpad enclosure must be >= 2.0 um
5984 0 BONDPAD.SP.2: Bondpad Metal10 to Metal10 spacing must be >= 3.0 um
5986 0 BONDPAD.E.1: Metal11 to Bondpad enclosure must be >= 2.0 um
5988 0 BONDPAD.E.1: Metal11 to Bondpad enclosure must be >= 2.0 um
5989 0 BONDPAD.SP.2: Bondpad Metal11 to Metal11 spacing must be >= 3.0 um
5992 0 BONDPAD.W.1: Bondpad width must be >= 55.0 um
5994 0 BONDPAD.W.1: Bondpad width must be >= 55.0 um
5996 0 BONDPAD.SP.1: Bondpad to Bondpad spacing must be >= 8.0 um
5998 0 BONDPAD.B.1B: Bondpad Metal1 beveled segments must be >= 1.8 um and <= 3.2 um
6000 0 BONDPAD.B.1B: Bondpad Metal2 beveled segments must be >= 1.8 um and <= 3.2 um
6002 0 BONDPAD.B.1B: Bondpad Metal3 beveled segments must be >= 1.8 um and <= 3.2 um
6004 0 BONDPAD.B.1B: Bondpad Metal4 beveled segments must be >= 1.8 um and <= 3.2 um
6006 0 BONDPAD.B.1B: Bondpad Metal5 beveled segments must be >= 1.8 um and <= 3.2 um
6008 0 BONDPAD.B.1B: Bondpad Metal6 beveled segments must be >= 1.8 um and <= 3.2 um
6010 0 BONDPAD.B.1B: Bondpad Metal7 beveled segments must be >= 1.8 um and <= 3.2 um
6012 0 BONDPAD.B.1B: Bondpad Metal8 beveled segments must be >= 1.8 um and <= 3.2 um
6014 0 BONDPAD.B.1B: Bondpad Metal9 beveled segments must be >= 1.8 um and <= 3.2 um
6016 0 BONDPAD.B.1B: Bondpad Metal10 beveled segments must be >= 1.8 um and <= 3.2 um
6018 0 BONDPAD.B.1B: Bondpad Metal11 beveled segments must be >= 1.8 um and <= 3.2 um
6021 0 BONDPAD.SP.3: Bondpad Via1 to Bondpad Via1 spacing must be >= 0.22 um
6024 0 BONDPAD.SP.3: Bondpad Via2 to Bondpad Via2 spacing must be >= 0.22 um
6027 0 BONDPAD.SP.3: Bondpad Via3 to Bondpad Via3 spacing must be >= 0.22 um
6030 0 BONDPAD.SP.3: Bondpad Via4 to Bondpad Via4 spacing must be >= 0.22 um
6033 0 BONDPAD.SP.3: Bondpad Via5 to Bondpad Via5 spacing must be >= 0.22 um
6036 0 BONDPAD.SP.3: Bondpad Via6 to Bondpad Via6 spacing must be >= 0.22 um
6039 0 BONDPAD.SP.4: Bondpad Via7 to Bondpad Via7 spacing must be >= 0.22 um
6042 0 BONDPAD.SP.4: Bondpad Via8 to Bondpad Via8 spacing must be >= 0.22 um
6045 0 BONDPAD.SP.4: Bondpad Via9 to Bondpad Via9 spacing must be >= 0.54 um
6048 0 BONDPAD.SP.4: Bondpad Via10 to Bondpad Via10 spacing must be >= 0.54 um
6050 0 BONDPAD.E.2: Bondpad Metal1 to Via1 enclosure must be >= 0.05 um
6052 0 BONDPAD.E.2: Bondpad Metal1 to Via1 enclosure must be >= 0.05 um
6054 0 BONDPAD.E.2: Bondpad Metal2 to Via2 enclosure must be >= 0.05 um
6056 0 BONDPAD.E.2: Bondpad Metal2 to Via2 enclosure must be >= 0.05 um
6058 0 BONDPAD.E.2: Bondpad Metal3 to Via3 enclosure must be >= 0.05 um
6060 0 BONDPAD.E.2: Bondpad Metal3 to Via3 enclosure must be >= 0.05 um
6062 0 BONDPAD.E.2: Bondpad Metal4 to Via4 enclosure must be >= 0.05 um
6064 0 BONDPAD.E.2: Bondpad Metal4 to Via4 enclosure must be >= 0.05 um
6066 0 BONDPAD.E.2: Bondpad Metal5 to Via5 enclosure must be >= 0.05 um
6068 0 BONDPAD.E.2: Bondpad Metal5 to Via5 enclosure must be >= 0.05 um
6070 0 BONDPAD.E.2: Bondpad Metal6 to Via6 enclosure must be >= 0.05 um
6072 0 BONDPAD.E.2: Bondpad Metal6 to Via6 enclosure must be >= 0.05 um
6074 0 BONDPAD.E.3: Bondpad Metal7 to Via7 enclosure must be >= 0.05 um
6076 0 BONDPAD.E.3: Bondpad Metal7 to Via7 enclosure must be >= 0.05 um
6078 0 BONDPAD.E.3: Bondpad Metal8 to Via8 enclosure must be >= 0.05 um
6080 0 BONDPAD.E.3: Bondpad Metal8 to Via8 enclosure must be >= 0.05 um
6082 0 BONDPAD.E.3: Bondpad Metal9 to Via9 enclosure must be >= 0.09 um
6084 0 BONDPAD.E.3: Bondpad Metal9 to Via9 enclosure must be >= 0.09 um
6086 0 BONDPAD.E.3: Bondpad Metal9 to Via10 enclosure must be >= 0.09 um
6088 0 BONDPAD.E.3: Bondpad Metal9 to Via10 enclosure must be >= 0.09 um
6090 0 BONDPAD.E.2: Bondpad Metal2 to Via1 enclosure must be >= 0.05 um
6092 0 BONDPAD.E.2: Bondpad Metal2 to Via1 enclosure must be >= 0.05 um
6094 0 BONDPAD.E.2: Bondpad Metal3 to Via2 enclosure must be >= 0.05 um
6096 0 BONDPAD.E.2: Bondpad Metal3 to Via2 enclosure must be >= 0.05 um
6098 0 BONDPAD.E.2: Bondpad Metal4 to Via3 enclosure must be >= 0.05 um
6100 0 BONDPAD.E.2: Bondpad Metal4 to Via3 enclosure must be >= 0.05 um
6102 0 BONDPAD.E.2: Bondpad Metal5 to Via4 enclosure must be >= 0.05 um
6104 0 BONDPAD.E.2: Bondpad Metal5 to Via4 enclosure must be >= 0.05 um
6106 0 BONDPAD.E.2: Bondpad Metal6 to Via5 enclosure must be >= 0.05 um
6108 0 BONDPAD.E.2: Bondpad Metal6 to Via5 enclosure must be >= 0.05 um
6110 0 BONDPAD.E.2: Bondpad Metal7 to Via6 enclosure must be >= 0.05 um
6112 0 BONDPAD.E.2: Bondpad Metal7 to Via6 enclosure must be >= 0.05 um
6114 0 BONDPAD.E.3: Bondpad Metal8 to Via7 enclosure must be >= 0.05 um
6116 0 BONDPAD.E.3: Bondpad Metal8 to Via7 enclosure must be >= 0.05 um
6118 0 BONDPAD.E.3: Bondpad Metal9 to Via8 enclosure must be >= 0.05 um
6120 0 BONDPAD.E.3: Bondpad Metal9 to Via8 enclosure must be >= 0.05 um
6122 0 BONDPAD.E.3: Bondpad Metal10 to Via9 enclosure must be >= 0.09 um
6124 0 BONDPAD.E.3: Bondpad Metal10 to Via9 enclosure must be >= 0.09 um
6126 0 BONDPAD.E.3: Bondpad Metal11 to Via10 enclosure must be >= 0.09 um
6128 0 BONDPAD.E.3: Bondpad Metal11 to Via10 enclosure must be >= 0.09 um
6129 0 BONDPAD.SP.6: Bondpad Metal1 to Bondpad Metal1 spacing across first slot must be >= 1.00 um and <= 3.50 um
6130 0 BONDPAD.SP.6: Bondpad Metal1 to Bondpad Metal1 spacing across first slot must be >= 1.00 um and <= 3.50 um
6131 0 BONDPAD.SP.6: Bondpad Metal2 to Bondpad Metal2 spacing across first slot must be >= 1.00 um and <= 3.50 um
6132 0 BONDPAD.SP.6: Bondpad Metal2 to Bondpad Metal2 spacing across first slot must be >= 1.00 um and <= 3.50 um
6133 0 BONDPAD.SP.6: Bondpad Metal3 to Bondpad Metal3 spacing across first slot must be >= 1.00 um and <= 3.50 um
6134 0 BONDPAD.SP.6: Bondpad Metal3 to Bondpad Metal3 spacing across first slot must be >= 1.00 um and <= 3.50 um
6135 0 BONDPAD.SP.6: Bondpad Metal4 to Bondpad Metal4 spacing across first slot must be >= 1.00 um and <= 3.50 um
6136 0 BONDPAD.SP.6: Bondpad Metal4 to Bondpad Metal4 spacing across first slot must be >= 1.00 um and <= 3.50 um
6137 0 BONDPAD.SP.6: Bondpad Metal5 to Bondpad Metal5 spacing across first slot must be >= 1.00 um and <= 3.50 um
6138 0 BONDPAD.SP.6: Bondpad Metal5 to Bondpad Metal5 spacing across first slot must be >= 1.00 um and <= 3.50 um
6139 0 BONDPAD.SP.6: Bondpad Metal6 to Bondpad Metal6 spacing across first slot must be >= 1.00 um and <= 3.50 um
6140 0 BONDPAD.SP.6: Bondpad Metal6 to Bondpad Metal6 spacing across first slot must be >= 1.00 um and <= 3.50 um
6141 0 BONDPAD.SP.6: Bondpad Metal7 to Bondpad Metal7 spacing across first slot must be >= 1.00 um and <= 3.50 um
6142 0 BONDPAD.SP.6: Bondpad Metal7 to Bondpad Metal7 spacing across first slot must be >= 1.00 um and <= 3.50 um
6143 0 BONDPAD.SP.6: Bondpad Metal8 to Bondpad Metal8 spacing across first slot must be >= 1.00 um and <= 3.50 um
6144 0 BONDPAD.SP.6: Bondpad Metal8 to Bondpad Metal8 spacing across first slot must be >= 1.00 um and <= 3.50 um
6145 0 BONDPAD.SP.6: Bondpad Metal9 to Bondpad Metal9 spacing across first slot must be >= 1.00 um and <= 3.50 um
6146 0 BONDPAD.SP.6: Bondpad Metal9 to Bondpad Metal9 spacing across first slot must be >= 1.00 um and <= 3.50 um
6147 0 BONDPAD.SP.6: Bondpad Metal10 to Bondpad Metal10 spacing across first slot must be >= 1.00 um and <= 3.50 um
6148 0 BONDPAD.SP.6: Bondpad Metal10 to Bondpad Metal10 spacing across first slot must be >= 1.00 um and <= 3.50 um
6150 0 BONDPAD.SP.7: Bondpad Via1 array to Bondpad Via1 array spacing must be >= 1.1 um
6152 0 BONDPAD.SP.7: Bondpad Via2 array to Bondpad Via2 array spacing must be >= 1.1 um
6154 0 BONDPAD.SP.7: Bondpad Via3 array to Bondpad Via3 array spacing must be >= 1.1 um
6156 0 BONDPAD.SP.7: Bondpad Via4 array to Bondpad Via4 array spacing must be >= 1.1 um
6158 0 BONDPAD.SP.7: Bondpad Via5 array to Bondpad Via5 array spacing must be >= 1.1 um
6160 0 BONDPAD.SP.7: Bondpad Via6 array to Bondpad Via6 array spacing must be >= 1.1 um
6162 0 BONDPAD.SP.7: Bondpad Via7 array to Bondpad Via7 array spacing must be >= 1.1 um
6164 0 BONDPAD.SP.7: Bondpad Via8 array to Bondpad Via8 array spacing must be >= 1.1 um
6166 0 BONDPAD.SP.7: Bondpad Via9 array to Bondpad Via9 array spacing must be >= 1.1 um
6168 0 BONDPAD.SP.7: Bondpad Via10 array to Bondpad Via10 array spacing must be >= 1.1 um
6171 0 OXIDER.W.1.1: Minimum Active Resistor width >= 0.1 um
6174 0 POLYR.W.1.1: Minimum Poly resistor width >= 0.1 um
